version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"  # Map host port 9000 to container port 9000
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:gI35qfuKbMgLlpssQff6Ivmh9t1xkycH27zllWff1Ko=
